apiVersion: v1
kind: Pod
metadata:
  name: data-transfer-pod
spec:
  containers:
  - name: data-transfer-pod
    image: nginx
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
    volumeMounts:
      - name: cephfs
        mountPath: /data
  volumes:
    - name: cephfs
      persistentVolumeClaim:
        claimName: cephfs-pvc
        readOnly: false
