apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: kube-mondrian
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: kube-mondrian:latest
  imagePullPolicy: IfNotPresent
  mainApplicationFile: local:///mondrian/anonymize.py
  deps:
    pyFiles:
      - local:///mondrian/mondrian.zip
  arguments:
    - /data/config/adults.json  # config file
    - "4"  # workers
    - "0"  # demo
    - "0"  # test
  sparkVersion: "3.5.0"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "2g"
    serviceAccount: spark-operator-spark
    volumeMounts:
      - name: kube-mondrian-storage
        mountPath: /data
  executor:
    cores: 1
    instances: 4
    memory: "2g"
    volumeMounts:
      - name: kube-mondrian-storage
        mountPath: /data
  volumes:
    - name: kube-mondrian-storage
      persistentVolumeClaim:
        claimName: cephfs-pvc
  sparkConf:
    #spark.ui.port: "4045"
    #spark.eventLog.enabled: "true"
    #spark.eventLog.dir": "/data/spark-events"
    spark.scheduler.mode: "FIFO"
    spark.default.parallelism: "4"
    spark.sql.shuffle.partitions: "4"
