apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-mondrian-volume
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  hostPath:
    path: "/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-mondrian-claim
spec:
  resources:
    requests:
      storage: 3Gi
  accessModes:
    - ReadWriteMany
  storageClassName: manual
